In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 载入数据

In [2]:
!ls ../dataset/app/

new_user_sensor.csv new_user_step.csv   old_user_sensor.csv old_user_step.csv

In [3]:
new_df = pd.read_csv('../dataset/app/new_user_step.csv')
new_df.head()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,step_too_fast_5,step_too_fast_10,step_too_fast_20,step_too_fast_50,step_too_fast_100,step_too_fast_200,step_too_fast_500,step_too_fast_1000,版本号,device_model
0,179495704,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,2018071100,HUAWEI VNS-L31
1,180031408,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2018072000,Redmi 4A
2,180031417,0,0,0,0,0,0,0,0,47,...,7,1,0,0,0,0,0,0,2018062500,SM-G930F
3,180031429,0,0,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,2018062500,vivo 1611
4,180031531,0,0,0,0,0,0,0,0,0,...,4,2,0,0,0,0,0,0,2018072000,ANE-AL00

In [4]:
new_df.shape

(2551, 24)

In [5]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2551 entries, 0 to 2550
Data columns (total 24 columns):
account_id            2551 non-null int64
neg                   2551 non-null int64
big                   2551 non-null int64
big_100_000_000       2551 non-null int64
time_neg              2551 non-null int64
step_diff_too_big     2551 non-null int64
step_desc             2551 non-null int64
step_desc_100         2551 non-null int64
step_desc_1000        2551 non-null int64
time_desc             2551 non-null int64
time_desc_1m          2551 non-null int64
time_desc_1h          2551 non-null int64
time_desc_1d          2551 non-null int64
step_too_fast         2551 non-null int64
step_too_fast_5       2551 non-null int64
step_too_fast_10      2551 non-null int64
step_too_fast_20      2551 non-null int64
step_too_fast_50      2551 non-null int64
step_too_fast_100     2551 non-null int64
step_too_fast_200     2551 non-null int64
step_too_fast_500     2551 non-null int64
step_too_fast_1000    2551 non-null int64
版本号                   2548 non-null object
device_model          2548 non-null object
dtypes: int64(22), object(2)
memory usage: 478.4+ KB

In [6]:
new_df2 = pd.read_csv('../dataset/app/new_user_sensor.csv')
new_df2.head()

,account-id,zip文件大小,sensor文件大小,总共sensor数量,平均每秒sensor数,每秒zip文件大小,活跃时间(ms),brand,device_model,0~4次每秒,...,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,account_id,步数相同的sensor,总sensor数,比例,Unnamed: 20
0,180058138,587535,2,0,0.0,0.0,0,google,Pixel,NaN,...,NaN,NaN,NaN,NaN,NaN,180058138,0.00,0.00,#DIV/0!,NaN
1,180100954,423377,2,0,0.0,0.0,0,samsung,SM-N950U,NaN,...,NaN,NaN,NaN,NaN,NaN,180100954,0.00,0.00,#DIV/0!,NaN
2,180033970,312769,2,0,0.0,0.0,0,samsung,SM-G920F,NaN,...,NaN,NaN,NaN,NaN,NaN,180033970,0.00,0.00,#DIV/0!,NaN
3,180075871,297910,2,0,0.0,0.0,0,MetroPCS,LGMP450,NaN,...,NaN,NaN,NaN,NaN,NaN,180075871,0.00,0.00,#DIV/0!,NaN
4,180172168,289928,2,0,0.0,0.0,0,vivo,vivo 1606,NaN,...,NaN,NaN,NaN,NaN,NaN,180172168,0.00,0.00,#DIV/0!,NaN

In [7]:
new_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2551 entries, 0 to 2550
Data columns (total 21 columns):
account-id      2551 non-null int64
zip文件大小         2551 non-null int64
sensor文件大小      2551 non-null int64
总共sensor数量      2551 non-null int64
平均每秒sensor数     2551 non-null float64
每秒zip文件大小       2551 non-null float64
活跃时间(ms)        2551 non-null int64
brand           2542 non-null object
device_model    2548 non-null object
0~4次每秒          2440 non-null float64
5~9次每秒          2440 non-null float64
10~19次每秒        2440 non-null float64
20~49次每秒        2440 non-null float64
50~99次每秒        2440 non-null float64
100~199次每秒      2440 non-null float64
200~more        2440 non-null float64
account_id      2551 non-null int64
步数相同的sensor     2551 non-null object
总sensor数        2551 non-null object
比例              2551 non-null object
Unnamed: 20     5 non-null object
dtypes: float64(9), int64(6), object(6)
memory usage: 418.6+ KB

In [8]:
new_df = new_df.merge(new_df2)
new_df.head()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,步数相同的sensor,总sensor数,比例,Unnamed: 20
0,179495704,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,68.00,75.00,90.67%,NaN
1,180031408,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.00,14.00,35.71%,NaN
2,180031417,0,0,0,0,0,0,0,0,47,...,0.0,0.0,0.0,0.0,0.0,0.0,78.00,"5,144.00",1.52%,NaN
3,180031429,0,0,0,0,0,0,0,0,10,...,12.0,0.0,0.0,0.0,0.0,0.0,16.00,714.00,2.24%,NaN
4,180031531,0,0,0,0,0,0,0,0,0,...,25.0,7.0,6.0,0.0,0.0,0.0,"2,120.00","3,551.00",59.70%,NaN

In [9]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2551 entries, 0 to 2550
Data columns (total 43 columns):
account_id            2551 non-null int64
neg                   2551 non-null int64
big                   2551 non-null int64
big_100_000_000       2551 non-null int64
time_neg              2551 non-null int64
step_diff_too_big     2551 non-null int64
step_desc             2551 non-null int64
step_desc_100         2551 non-null int64
step_desc_1000        2551 non-null int64
time_desc             2551 non-null int64
time_desc_1m          2551 non-null int64
time_desc_1h          2551 non-null int64
time_desc_1d          2551 non-null int64
step_too_fast         2551 non-null int64
step_too_fast_5       2551 non-null int64
step_too_fast_10      2551 non-null int64
step_too_fast_20      2551 non-null int64
step_too_fast_50      2551 non-null int64
step_too_fast_100     2551 non-null int64
step_too_fast_200     2551 non-null int64
step_too_fast_500     2551 non-null int64
step_too_fast_1000    2551 non-null int64
版本号                   2548 non-null object
device_model          2548 non-null object
account-id            2551 non-null int64
zip文件大小               2551 non-null int64
sensor文件大小            2551 non-null int64
总共sensor数量            2551 non-null int64
平均每秒sensor数           2551 non-null float64
每秒zip文件大小             2551 non-null float64
活跃时间(ms)              2551 non-null int64
brand                 2542 non-null object
0~4次每秒                2440 non-null float64
5~9次每秒                2440 non-null float64
10~19次每秒              2440 non-null float64
20~49次每秒              2440 non-null float64
50~99次每秒              2440 non-null float64
100~199次每秒            2440 non-null float64
200~more              2440 non-null float64
步数相同的sensor           2551 non-null object
总sensor数              2551 non-null object
比例                    2551 non-null object
Unnamed: 20           5 non-null object
dtypes: float64(9), int64(27), object(7)
memory usage: 876.9+ KB

In [10]:
old_df = pd.read_csv('../dataset/app/old_user_step.csv')
old_df.head()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,step_too_fast_5,step_too_fast_10,step_too_fast_20,step_too_fast_50,step_too_fast_100,step_too_fast_200,step_too_fast_500,step_too_fast_1000,版本号,device_model
0,94708582,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,p5.5.1,SM-A320FL
1,165685081,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,2018052500,LM-X415K
2,171675541,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,p5.5.1,LG-F800L
3,154088011,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,p5.4.1,LG-LS777
4,149399431,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,p5.4.1,SM-G935F

In [11]:
old_df2 = pd.read_csv('../dataset/app/old_user_sensor.csv')
old_df2.head()

,account-id,zip文件大小,sensor文件大小,总共sensor数量,平均每秒sensor数,每秒zip文件大小,活跃时间(ms),brand,device_model,0~4次每秒,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,account_id,步数相同的sensor,总sensor数,比例
0,171736561,75960,875,7,1.0,10851.0,7000,NaN,SM-A520F,7.0,0.0,0.0,0.0,0.0,0.0,0.0,171736561,7,7,100.00%
1,139687771,30390,372,3,1.0,10130.0,3000,NaN,MI MAX 2,3.0,0.0,0.0,0.0,0.0,0.0,0.0,139687771,3,3,100.00%
2,164285371,179619,1000,8,1.0,22452.0,8000,NaN,SM-G928F,8.0,0.0,0.0,0.0,0.0,0.0,0.0,164285371,8,8,100.00%
3,153812890,14533,368,3,1.0,4844.0,3000,NaN,Moto G (4),3.0,0.0,0.0,0.0,0.0,0.0,0.0,153812890,3,3,100.00%
4,160991620,123295,252,2,1.0,61647.0,2000,NaN,SM-G920V,2.0,0.0,0.0,0.0,0.0,0.0,0.0,160991620,2,2,100.00%

In [12]:
old_df = old_df.merge(old_df2)

In [13]:
old_df.head()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,0~4次每秒,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,步数相同的sensor,总sensor数,比例
0,94708582,0,0,0,0,0,0,0,0,0,...,1202.0,2.0,0.0,0.0,0.0,0.0,0.0,40,2456,1.63%
1,165685081,0,0,0,0,0,0,0,0,2,...,1550.0,16.0,0.0,0.0,0.0,0.0,0.0,65,4127,1.57%
2,171675541,0,0,0,0,0,0,0,0,0,...,2906.0,6.0,0.0,0.0,0.0,0.0,0.0,87,5724,1.52%
3,154088011,0,0,0,0,0,0,0,0,3,...,1801.0,23.0,0.0,0.0,0.0,0.0,0.0,150,3521,4.26%
4,149399431,0,0,0,0,0,0,0,0,0,...,630.0,1.0,0.0,0.0,0.0,0.0,0.0,88,1167,7.54%

In [14]:
old_df.shape

(2591, 42)

In [15]:
new_df.shape

(2551, 43)

# 数据清洗
## 概况

In [16]:
new_df.describe()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,平均每秒sensor数,每秒zip文件大小,活跃时间(ms),0~4次每秒,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more
count,2.551000e+03,2551.0,2551.00000,2551.000000,2551.000000,2551.000000,2551.000000,2551.000000,2551.000000,2551.000000,...,2551.000000,2551.000000,2.551000e+03,2440.000000,2440.000000,2440.000000,2440.000000,2440.000000,2440.000000,2440.000000
mean,1.801028e+08,0.0,2.76715,0.310466,0.000392,0.005488,0.102313,0.059976,0.030968,2.775774,...,1.617380,1086.274065,1.508468e+06,952.347951,258.724180,2.955738,0.707787,7.638934,34.766803,0.014344
std,4.310629e+04,0.0,124.32806,7.934489,0.019799,0.207623,1.998264,1.058268,0.725057,12.150329,...,3.467256,5967.233312,4.995206e+06,2093.019645,3156.374479,47.389764,5.183894,347.122360,1603.558451,0.297935
min,1.794957e+08,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.800680e+08,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.088144,101.164710,1.337630e+05,147.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.801045e+08,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.487803,160.722825,5.956240e+05,485.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.801337e+08,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,1.684124,360.671265,1.465546e+06,1159.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.801822e+08,0.0,6267.00000,306.000000,1.000000,10.000000,66.000000,29.000000,29.000000,233.000000,...,99.694251,142743.000000,9.735410e+07,48173.000000,82179.000000,1975.000000,126.000000,17131.000000,79113.000000,12.000000

In [17]:
old_df.describe()

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,活跃时间(ms),0~4次每秒,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,步数相同的sensor,总sensor数
count,2.591000e+03,2591.0,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,...,2.591000e+03,2135.00000,2135.000000,2135.000000,2135.000000,2135.000000,2135.000000,2135.000000,2591.000000,2591.000000
mean,1.437165e+08,0.0,1.527596,0.405249,0.010421,0.046700,0.105365,0.050946,0.028946,2.998070,...,2.208858e+06,1843.31007,291.655738,1.403279,0.393443,0.099766,0.048244,0.023888,1578.834427,4405.612891
std,3.023981e+07,0.0,45.604637,20.627927,0.530432,2.318413,2.107922,1.197048,0.951493,12.248725,...,5.127138e+06,1870.73516,4208.684579,14.190988,4.584902,1.491266,0.803002,0.612958,22305.807521,22650.091805
min,4.401571e+06,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.297609e+08,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.199500e+05,621.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,293.000000
50%,1.530028e+08,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.248161e+06,1329.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,77.000000,1811.000000
75%,1.676592e+08,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,2.747202e+06,2463.50000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,183.000000,4236.000000
max,1.721460e+08,0.0,1630.000000,1050.000000,27.000000,118.000000,88.000000,48.000000,48.000000,225.000000,...,1.105714e+08,28059.00000,94697.000000,329.000000,135.000000,60.000000,29.000000,24.000000,546272.000000,546931.000000

## 缺失值

In [18]:
new_df.isna().sum()

account_id               0
neg                      0
big                      0
big_100_000_000          0
time_neg                 0
step_diff_too_big        0
step_desc                0
step_desc_100            0
step_desc_1000           0
time_desc                0
time_desc_1m             0
time_desc_1h             0
time_desc_1d             0
step_too_fast            0
step_too_fast_5          0
step_too_fast_10         0
step_too_fast_20         0
step_too_fast_50         0
step_too_fast_100        0
step_too_fast_200        0
step_too_fast_500        0
step_too_fast_1000       0
版本号                      3
device_model             3
account-id               0
zip文件大小                  0
sensor文件大小               0
总共sensor数量               0
平均每秒sensor数              0
每秒zip文件大小                0
活跃时间(ms)                 0
brand                    9
0~4次每秒                 111
5~9次每秒                 111
10~19次每秒               111
20~49次每秒               111
50~99次每秒               111
100~199次每秒             111
200~more               111
步数相同的sensor              0
总sensor数                 0
比例                       0
Unnamed: 20           2546
dtype: int64

In [19]:
# 品牌，版本号，手机型号虽然存在缺失值，但是并不是我们研究的重点。
# 每秒sensor数量相关存在111个缺失值，重点查看一下这部分数据。
new_df[new_df['0~4次每秒'].isna()]['总共sensor数量'].any()

False

In [20]:
# 这些'0~4次每秒'为缺失值的用户的'总共sensor数量'都是0。
# 因为没有sensor（传感器）数据，所以传感器数据的分布也应该都是0。
values = {'0~4次每秒': 0, '5~9次每秒': 0, '10~19次每秒': 0, \
          '20~49次每秒': 0, '50~99次每秒':0,'100~199次每秒':0,'200~more':0}
new_df.fillna(value=values, inplace=True)

In [21]:
new_df.drop(columns=['Unnamed: 20'], inplace=True)

In [22]:
new_df.isna().sum()

account_id            0
neg                   0
big                   0
big_100_000_000       0
time_neg              0
step_diff_too_big     0
step_desc             0
step_desc_100         0
step_desc_1000        0
time_desc             0
time_desc_1m          0
time_desc_1h          0
time_desc_1d          0
step_too_fast         0
step_too_fast_5       0
step_too_fast_10      0
step_too_fast_20      0
step_too_fast_50      0
step_too_fast_100     0
step_too_fast_200     0
step_too_fast_500     0
step_too_fast_1000    0
版本号                   3
device_model          3
account-id            0
zip文件大小               0
sensor文件大小            0
总共sensor数量            0
平均每秒sensor数           0
每秒zip文件大小             0
活跃时间(ms)              0
brand                 9
0~4次每秒                0
5~9次每秒                0
10~19次每秒              0
20~49次每秒              0
50~99次每秒              0
100~199次每秒            0
200~more              0
步数相同的sensor           0
总sensor数              0
比例                    0
dtype: int64

In [23]:
old_df.isna().sum()

account_id               0
neg                      0
big                      0
big_100_000_000          0
time_neg                 0
step_diff_too_big        0
step_desc                0
step_desc_100            0
step_desc_1000           0
time_desc                0
time_desc_1m             0
time_desc_1h             0
time_desc_1d             0
step_too_fast            0
step_too_fast_5          0
step_too_fast_10         0
step_too_fast_20         0
step_too_fast_50         0
step_too_fast_100        0
step_too_fast_200        0
step_too_fast_500        0
step_too_fast_1000       0
版本号                     14
device_model            14
account-id               0
zip文件大小                  0
sensor文件大小               0
总共sensor数量               0
平均每秒sensor数              0
每秒zip文件大小                0
活跃时间(ms)                 0
brand                 2289
0~4次每秒                 456
5~9次每秒                 456
10~19次每秒               456
20~49次每秒               456
50~99次每秒               456
100~199次每秒             456
200~more               456
步数相同的sensor              0
总sensor数                 0
比例                       0
dtype: int64

In [24]:
# 同样的查看每秒sensor数量相关的缺失值，重点查看一下这部分数据。
new_df[new_df['0~4次每秒'].isna()]['总共sensor数量'].sum()

0

In [25]:
old_df.fillna(value=values, inplace=True)
old_df.isna().sum()

account_id               0
neg                      0
big                      0
big_100_000_000          0
time_neg                 0
step_diff_too_big        0
step_desc                0
step_desc_100            0
step_desc_1000           0
time_desc                0
time_desc_1m             0
time_desc_1h             0
time_desc_1d             0
step_too_fast            0
step_too_fast_5          0
step_too_fast_10         0
step_too_fast_20         0
step_too_fast_50         0
step_too_fast_100        0
step_too_fast_200        0
step_too_fast_500        0
step_too_fast_1000       0
版本号                     14
device_model            14
account-id               0
zip文件大小                  0
sensor文件大小               0
总共sensor数量               0
平均每秒sensor数              0
每秒zip文件大小                0
活跃时间(ms)                 0
brand                 2289
0~4次每秒                   0
5~9次每秒                   0
10~19次每秒                 0
20~49次每秒                 0
50~99次每秒                 0
100~199次每秒               0
200~more                 0
步数相同的sensor              0
总sensor数                 0
比例                       0
dtype: int64

## 重复值

In [26]:
new_df.duplicated().sum()

0

In [27]:
old_df.duplicated().sum()

0

In [28]:
new_df.account_id.duplicated().sum()

0

# 探索性分析

In [58]:
# 计算z值
n_new = new_df.shape[0]
n_old = old_df.shape[0]

import math

def calculate_z(column, bigThenZero = True):
    if bigThenZero:
        count_new =  new_df[new_df[column]>0].loc[:,column].count()
        count_old =  old_df[old_df[column]>0].loc[:,column].count()
    else:
        count_new =  new_df[new_df[column]==0].loc[:,column].count()
        count_old =  old_df[old_df[column]==0].loc[:,column].count()
    p_new = count_new/n_new
    p_old = count_old/n_old
    q_new = 1 - p_new
    q_old = 1 - p_old
    z = (p_new - p_old)/math.sqrt(p_new*q_new/n_new + p_old*q_old/n_old)
    dict1 = {'count_new':count_new, 'p_new':p_new, 'count_old':count_old, 'p_old':p_old, 'z':z}
    return dict1

## 步数为负

In [30]:
new_df.neg.value_counts()

0    2551
Name: neg, dtype: int64

In [31]:
old_df.neg.value_counts()

0    2591
Name: neg, dtype: int64

## 时间为负

In [32]:
new_df.time_neg.value_counts()

0    2550
1       1
Name: time_neg, dtype: int64

In [33]:
old_df.time_neg.value_counts()

0     2590
27       1
Name: time_neg, dtype: int64

## 步数回退

In [34]:
new_df.step_desc.value_counts()

0     2519
1       16
2        4
3        2
6        2
4        2
61       1
29       1
19       1
66       1
26       1
10       1
Name: step_desc, dtype: int64

In [35]:
old_df.step_desc.value_counts()

0     2550
1       22
4        5
2        4
5        2
25       1
19       1
9        1
7        1
3        1
88       1
48       1
14       1
Name: step_desc, dtype: int64

In [59]:
calculate_z('step_desc')

{'count_new': 32,
 'p_new': 0.012544100352802822,
 'count_old': 41,
 'p_old': 0.015824006175221922,
 'z': -0.9949942346086498}

## 时间回退

In [37]:
new_df.time_desc.value_counts()

0      1904
1       168
2       102
3        59
4        40
       ...
49        1
88        1
78        1
68        1
233       1
Name: time_desc, Length: 70, dtype: int64

In [38]:
calculate_z('time_desc')

{'count_new': 647,
 'p_new': 0.25362602900823206,
 'count_old': 700,
 'p_old': 0.27016595908915475,
 'z': -1.3491015145430236}

## 大数
### 上限为1,000,000

In [39]:
new_df.big.value_counts()

0       2543
187        1
123        1
27         1
21         1
306        1
126        1
6267       1
2          1
Name: big, dtype: int64

In [40]:
old_df.big.value_counts()

0       2588
1630       1
1278       1
1050       1
Name: big, dtype: int64

In [41]:
calculate_z('big')

{'count_new': 8,
 'p_new': 0.0031360250882007056,
 'count_old': 3,
 'p_old': 0.0011578541103820917,
 'z': 1.5299146208096965}

### 上限为100,000,000

In [42]:
calculate_z('big_100_000_000')

{'count_new': 7,
 'p_new': 0.0027440219521756176,
 'count_old': 1,
 'p_old': 0.00038595137012736397,
 'z': 2.1334855478910137}

In [43]:
old_df[old_df.big>0].big.count(), old_df[old_df.big>0].big.count()/old_df.big.count()

(3, 0.0011578541103820917)

In [56]:
new_df[new_df.big_100_000_000>0]['device_model']

539     Lenovo A7020a48
566     Lenovo A7020a48
700     Lenovo A7020a48
827     Lenovo A7020a48
945     Lenovo A7020a48
2195           SM-S906L
2297    Lenovo A7020a48
Name: device_model, dtype: object

## 步数差过大

In [45]:
new_df.step_diff_too_big.value_counts()

0     2548
3        1
1        1
10       1
Name: step_diff_too_big, dtype: int64

In [46]:
old_df.step_diff_too_big.value_counts()

0      2587
1         3
118       1
Name: step_diff_too_big, dtype: int64

In [47]:
calculate_z('step_diff_too_big')

{'count_new': 3,
 'p_new': 0.0011760094080752645,
 'count_old': 4,
 'p_old': 0.0015438054805094559,
 'z': -0.35801767079126473}

## 速度过快

In [48]:
new_df.step_too_fast_5.value_counts()

0      1894
1       203
2       110
3        61
4        54
       ...
136       1
110       1
100       1
98        1
218       1
Name: step_too_fast_5, Length: 64, dtype: int64

In [49]:
# 一秒5步
calculate_z('step_too_fast_5')

{'count_new': 657,
 'p_new': 0.25754606036848293,
 'count_old': 782,
 'p_old': 0.3018139714395986,
 'z': -3.541026506973559}

In [50]:
# 一秒10步
calculate_z('step_too_fast_10')

{'count_new': 298,
 'p_new': 0.11681693453547629,
 'count_old': 343,
 'p_old': 0.13238131995368582,
 'z': -1.6904605788422309}

In [51]:
# 一秒20步
calculate_z('step_too_fast_20')

{'count_new': 174,
 'p_new': 0.06820854566836534,
 'count_old': 210,
 'p_old': 0.08104978772674643,
 'z': -1.7529968021466893}

In [52]:
# 一秒50步
calculate_z('step_too_fast_50')

{'count_new': 111,
 'p_new': 0.04351234809878479,
 'count_old': 131,
 'p_old': 0.05055962948668468,
 'z': -1.1939101552094378}

In [53]:
# 一秒100步
calculate_z('step_too_fast_100')

{'count_new': 62,
 'p_new': 0.024304194433555467,
 'count_old': 70,
 'p_old': 0.027016595908915475,
 'z': -0.6151668847920234}

In [64]:
# 一秒200步
calculate_z('step_too_fast_200')

{'count_new': 32,
 'p_new': 0.012544100352802822,
 'count_old': 29,
 'p_old': 0.011192589733693555,
 'z': 0.4473560575886766}

In [65]:
# 一秒200步
calculate_z('step_too_fast_1000')

{'count_new': 8,
 'p_new': 0.0031360250882007056,
 'count_old': 3,
 'p_old': 0.0011578541103820917,
 'z': 1.5299146208096965}

## sensor总数

In [63]:
calculate_z('总共sensor数量', bigThenZero=False)

{'count_new': 111,
 'p_new': 0.04351234809878479,
 'count_old': 456,
 'p_old': 0.17599382477807796,
 'z': -15.582233253382972}

In [66]:
# sensor问题怎么会老用户空白的更多呢？而且拿出来一个看了，也不对啊。
old_df[old_df['总共sensor数量']==0]

,account_id,neg,big,big_100_000_000,time_neg,step_diff_too_big,step_desc,step_desc_100,step_desc_1000,time_desc,...,0~4次每秒,5~9次每秒,10~19次每秒,20~49次每秒,50~99次每秒,100~199次每秒,200~more,步数相同的sensor,总sensor数,比例
6,165277390,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
12,85870378,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
25,168913372,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
27,164856829,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
28,144166240,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,163175329,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
2568,165244330,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
2585,164119810,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
2586,99901291,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!
2588,165825091,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,#DIV/0!